config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  controller :pages do
    get "about-us", action: "about_us"
    get "managers-page", action: "managers_page"
    get "manager-one", action: "manager_one"
    get "apartaments-page", action: "apartaments_page"
    get "contacts", action: "contacts"
    get "apartaments-one", action: "apartaments_one"
    get "comparison-page", action: "comparison_page"
  end

  match "*url", to: "application#render_not_found", via: :all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # include ActionView::Helpers::OutputSafetyHelper
  # include ActionView::Helpers::AssetUrlHelper
  # include ActionView::Helpers::TagHelper
  # include ActionView::Helpers::UrlHelper
  # include Cms::Helpers::PagesHelper
  # include Cms::Helpers::MetaDataHelper
  # include Cms::Helpers::NavigationHelper
  # include Cms::Helpers::ActionView::UrlHelper

  def render_not_found
    @render_header = false
    @render_footer = false
    render template: "errors/not_found.html.slim", status: 404

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about_us
  end

  def managers_page
  end

  def manager_one
  end

  def apartaments_page
  end

  def contacts
  end

  def apartaments_one    
  end
  
  def comparison_page
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_all_managers_wrap.html.slim
.our-managers-wrap.section-indent
  .row
    .columns
      p.section-title наші менеджери
      - count_items = 8
      - if page_name == "index" || page_name == "managers"  || page_name == "about-us"
        p.section-sub-title професійні менеджери, які допоможуть та порадять вам обрати саме те що ви шукали
      - elsif page_name == "contacts" || page_name == "about-us"
        - count_items = 4

  - if page_name == "managers"
      
    .filter-manager-wrap
      .row
        .columns.medium-6
        
          form
            .input-field.width-bottom-border
              input#serch-manager name="search" 
              label ПОШУК МЕНЕДЖЕРА
              span.bar
              button.svg = inline_svg "svg/search.svg"
              

        .columns.medium-3
          select placeholder="тип нерухомості"
            option data-display="" Оберіть місто
            option value="1" Львів
            option value="2" Стрий

  .row.columns-left
    .columns.medium-6.large-3
      .one-manager
        .square 
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-01.jpg')})"
          .call-popup-box.orange-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам

              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"


        .info-manager
          .inner
            .call-us.orange-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.orange Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.orange
                  |@
                |matis.com

            .title.orange бінес нерухомість
            .sity Львів

    .columns.medium-6.large-3
      .one-manager
        .square 
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-02.jpg')})"
          .call-popup-box.blue-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам
              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"

        .info-manager
          .inner
            .call-us.blue-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.blue Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.blue
                  |@
                |matis.com

            .title.blue житлова нерухомість
            .sity Львів

    .columns.medium-6.large-3
      .one-manager
        .square 
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-03.jpg')})"
          .call-popup-box.orange-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам

              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"

                  
        .info-manager
          .inner
            .call-us.orange-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.orange Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.orange
                  |@
                |matis.com

            .title.orange бінес нерухомість
            .sity Львів

    .columns.medium-6.large-3
      .one-manager
        .square
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-04.jpg')})"
          .call-popup-box.blue-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам
              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"

        .info-manager
          .inner
            .call-us.blue-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.blue Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.blue
                  |@
                |matis.com

            .title.blue житлова нерухомість
            .sity Львів


    .columns.medium-6.large-3
      .one-manager
        .square
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-05.jpg')})"
          .call-popup-box.orange-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам

              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"

                  
        .info-manager
          .inner
            .call-us.orange-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.orange Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.orange
                  |@
                |matis.com

            .title.orange бінес нерухомість
            .sity Львів

    .columns.medium-6.large-3
      .one-manager
        .square
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-06.jpg')})"
          .call-popup-box.blue-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам
              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"

        .info-manager
          .inner
            .call-us.blue-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.blue Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.blue
                  |@
                |matis.com

            .title.blue житлова нерухомість
            .sity Львів

    .columns.medium-6.large-3
      .one-manager
        .square
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-03.jpg')})"
          .call-popup-box.orange-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам

              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"

                  
        .info-manager
          .inner
            .call-us.orange-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.orange Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.orange
                  |@
                |matis.com

            .title.orange бінес нерухомість
            .sity Львів

    .columns.medium-6.large-3
      .one-manager
        .square
          a.img-bg href=manager_one_path style="background-image: url(#{asset_path('img/manager-01.jpg')})"
          .call-popup-box.blue-bg
            .inner-popup
              .title Замовлення дзвінка
              .text 
                | Введіть ваш номер телефону та 
                span
                  | Дарт 
                | передзвонить вам
              form
                .input-field
                  input#first_name name="number"
                  label Ваш номер телефону?
                  span.bar
                  button.svg = inline_svg "svg/arrow_right.svg"

        .info-manager
          .inner
            .call-us.blue-bg
              .phone-box = inline_svg "svg/telephone.svg"
              .close-popup-box = inline_svg "svg/close.svg"
            h3.name.blue Вейдер
            h4.surname Дарт

            .call-box
              a.number.regular href="+380 96 458 7854" +380 96 458 7854
              a.number.regular href="+380 67 451 4568" +380 67 451 4568

            .mail-box
              a.mail.regular href="/" 
                |dart
                span.blue
                  |@
                |matis.com

            .title.blue житлова нерухомість
            .sity Львів

  a.button.blue-bg href=managers_page_path всі менеджери

app/views/application/_apartaments_filter_mobile.html.slim
.filter-mobile
  .head-container.blue-bg
    .inner
      .name-filter
        .title Фільтр
        .sub-title 
          |знайдено 
          span 21

      = inline_svg "svg/filter.svg"

  = render "filters_apartament"

  .button.blue-bg застосувати

app/views/application/_apartaments_filter_mobile_price.html.slim
.filter-mobile-price
  .head-container.blue-bg
    .inner
      .name-filter
        .title Сортуваня

      = inline_svg "svg/sort.svg"

  .filter-inner
    .radio-box
      input#1-option type="radio"  name="selector"
      label for="1-option" Ціна від більшої
      .check

    .radio-box
      input#2-option type="radio"  name="selector"
      label for="2-option" Ціна від меньшої
      .check

    .radio-box
      input#3-option type="radio"  name="selector"
      label for="3-option" По даті спочатку новіші
      .check

    .radio-box
      input#4-option type="radio"  name="selector"
      label for="4-option" По даті спочатку старші
      .check

  .button.blue-bg застосувати

app/views/application/_apartaments_filter_popup.html.slim
.apartaments-filter-popup
  
  .tabs-box.tab-buttons
    .tab-button.tab.in-popup.active житлова нерухамість
    .tab-button.tab.in-popup бізнес нерухомість

  .tab-content-wrapper
    .filters-content.tab-content.active
      .inner
        .row
          .large-4.medium-6.columns

            .head-title категорія і тип

            .checkbox-box
              .title Категорія
              .one-checkbox
                .checkbox
                  input#checkbox-salis type="checkbox" 
                  label.switcher-control for="checkbox-salis"
                    = inline_svg "svg/calendar.svg"
                    span продажа

              .one-checkbox
                .checkbox
                  input#checkbox-rent type="checkbox" 
                  label.switcher-control for="checkbox-rent"
                    = inline_svg "svg/money.svg"
                    span оренда
                
              .one-checkbox
                .checkbox
                  input#checkbox-rent-one type="checkbox" 
                  label.switcher-control for="checkbox-rent-one"
                    = inline_svg "svg/money.svg"
                    span Оренда подобова



            .checkbox-box
              .title Категорія
              .one-checkbox
                .checkbox
                  input#checkbox-apartaments type="checkbox" 
                  label.switcher-control for="checkbox-apartaments"
                    = inline_svg "svg/jut-1.svg"
                    span квартири

              .one-checkbox
                .checkbox
                  input#checkbox-hauses type="checkbox" 
                  label.switcher-control for="checkbox-hauses"
                    = inline_svg "svg/jut-3.svg"
                    span будинки

              .one-checkbox
                .checkbox
                  input#checkbox-lend type="checkbox" 
                  label.switcher-control for="checkbox-lend"
                    = inline_svg "svg/jut-2.1.svg"
                    span земля

          .large-4.medium-6.columns
            .head-title розташування
            .drop-down-box
              select placeholder="тип нерухомості"
                option data-display="" Nothing
                option value="1" житлова
                option value="2" бізнес

              select placeholder="тип нерухомості"
                option data-display="" Nothing
                option value="1" оренда
                option value="2" купівля

              select placeholder="тип нерухомості"
                option data-display="" Nothing
                option value="1" квартири
                option value="2" офіси

          .large-4.medium-6.columns
            .head-title ціна та площа

            .currency
              .sub-title Ціна:
              span.active грн 
              span usd

            .range-info
              .range-one
                .min-value
                  |від
                  span
                    | 150м
                    sup 2
                .max-value
                  | до
                  span
                    | 250м
                    sup 2
                .range-input-m.asRange


              .range-one
                .sub-title.no-padding Площа:
                .min-value
                  |від
                  span
                    | 150м
                    sup 2
                .max-value
                  | до
                  span
                    | 250м
                    sup 2
                .range-input-m.asRange



    .filters-content.tab-content
      .inner
        .row
          .medium-6.columns

            .head-title категорія і тип

            .checkbox-box
              .title Категорія
              .one-checkbox
                .checkbox
                  input#checkbox-salis type="checkbox" 
                  label.switcher-control for="checkbox-salis"
                    = inline_svg "svg/calendar.svg"
                    span продажа

              .one-checkbox
                .checkbox
                  input#checkbox-rent type="checkbox" 
                  label.switcher-control for="checkbox-rent"
                    = inline_svg "svg/money.svg"
                    span продажа

          .medium-6.columns
            .head-title розташування
            .drop-down-box
              select placeholder="тип нерухомості"
                option data-display="" Nothing
                option value="1" житлова
                option value="2" бізнес

              select placeholder="тип нерухомості"
                option data-display="" Nothing
                option value="1" оренда
                option value="2" купівля

              select placeholder="тип нерухомості"
                option data-display="" Nothing
                option value="1" квартири
                option value="2" офіси
  
     

     

     


          

  .button.blue-bg
    = inline_svg "svg/search.svg"
    |підібрати

app/views/application/_filters_apartament.html.slim
.filter-inner  
  .accordion-button
    span Вид операції:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"
  .accordion-inner
    .checkbox-box
      .one-checkbox
        .checkbox
          input#checkbox-salis1 type="checkbox" 
          label.switcher-control for="checkbox-salis1"
            = inline_svg "svg/calendar.svg"
            span продажа

      .one-checkbox
        .checkbox
          input#checkbox-rent1 type="checkbox" 
          label.switcher-control for="checkbox-rent1"
            = inline_svg "svg/money.svg"
            span оренда
        
      .one-checkbox
        .checkbox
          input#checkbox-rent-one1 type="checkbox" 
          label.switcher-control for="checkbox-rent-one1"
            = inline_svg "svg/money.svg"
            span Оренда подобова

  .accordion-button
    span Категорія:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"
  .accordion-inner
    .checkbox-box
      .one-checkbox
        .checkbox
          input#checkbox-apartaments1 type="checkbox" 
          label.switcher-control for="checkbox-apartaments1"
            = inline_svg "svg/jut-1.svg"
            span квартири

      .one-checkbox
        .checkbox
          input#checkbox-hauses1 type="checkbox" 
          label.switcher-control for="checkbox-hauses1"
            = inline_svg "svg/jut-3.svg"
            span будинки

      .one-checkbox
        .checkbox
          input#checkbox-lend type="checkbox" 
          label.switcher-control for="checkbox-lend"
            = inline_svg "svg/jut-2.1.svg"
            span земля

  .accordion-button
    span Тип:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"

  .accordion-inner
    .checkbox-box
      .inner
        .one-checkbox
          .checkbox
            input#checkbox-apartaments2 type="checkbox" 
            label.switcher-control for="checkbox-apartaments2"
              / = inline_svg "svg/jut-1.svg"
              span квартири

        .one-checkbox
          .checkbox
            input#checkbox-apartaments3 type="checkbox" 
            label.switcher-control for="checkbox-apartaments3"
              / = inline_svg "svg/jut-1.svg"
              span квартири


  .accordion-button
    span Розташування:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"

  .accordion-inner
    .inner
      .drop-down-box
        select placeholder="тип нерухомості"
          option data-display="" Оберіть облать
          option value="1" Львівська .обл
          option value="2" Київська .обл

        select placeholder="тип нерухомості"
          option data-display="" Місто
          option value="1" Львів
          option value="2" Київ


        select placeholder="тип нерухомості"
          option data-display="" Оберіть район
          option value="1" Франківський
          option value="2" Галицький

  .accordion-button
    span Ціна:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"

  .accordion-inner
    .inner
      .currency.in-general-filter
        span.active грн 
        span usd
      .range-info  
        .range-one
          .min-value
            |від
            span
              | 0
          .max-value
            | до
            span
              | 5600
          .range-input-m.asRange


  .accordion-button
    span Площа загальна:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"

  .accordion-inner
    .inner
      .range-info  
        .range-one
          .min-value
            |від
            span
              | 75м
              sup 2
          .max-value
            | до
            span
              | 650м
              sup 2
          .range-input-m.asRange

  .accordion-button
    span Кількість кімнат:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"

  .accordion-inner
    .inner
      .checkbox-box
        .one-checkbox.small-w
          .checkbox
            input#apartaments-room1 type="checkbox" 
            label.switcher-control for="apartaments-room1"
              / = inline_svg "svg/jut-1.svg"
              span 1
        .one-checkbox.small-w
          .checkbox
            input#apartaments-room2 type="checkbox" 
            label.switcher-control for="apartaments-room2"
              / = inline_svg "svg/jut-1.svg"
              span 2
        .one-checkbox.small-w
          .checkbox
            input#apartaments-room3 type="checkbox" 
            label.switcher-control for="apartaments-room3"
              / = inline_svg "svg/jut-1.svg"
              span 3
        .one-checkbox.small-w
          .checkbox
            input#apartaments-room4 type="checkbox" 
            label.switcher-control for="apartaments-room4"
              / = inline_svg "svg/jut-1.svg"
              span 4
        .one-checkbox.small-w
          .checkbox
            input#apartaments-room5 type="checkbox" 
            label.switcher-control for="apartaments-room5"
              / = inline_svg "svg/jut-1.svg"
              span 5
        .one-checkbox.small-w
          .checkbox
            input#apartaments-room6 type="checkbox" 
            label.switcher-control for="apartaments-room6"
              / = inline_svg "svg/jut-1.svg"
              span.large-w 6+

  .accordion-button
    span Поверх:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"

  .accordion-inner
    .inner
      .checkbox-box
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor1 type="checkbox" 
            label.switcher-control for="apartaments-floor1"
              / = inline_svg "svg/jut-1.svg"
              span 1
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor2 type="checkbox" 
            label.switcher-control for="apartaments-floor2"
              / = inline_svg "svg/jut-1.svg"
              span 2
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor3 type="checkbox" 
            label.switcher-control for="apartaments-floor3"
              / = inline_svg "svg/jut-1.svg"
              span 3
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor4 type="checkbox" 
            label.switcher-control for="apartaments-floor4"
              / = inline_svg "svg/jut-1.svg"
              span 4
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor5 type="checkbox" 
            label.switcher-control for="apartaments-floor5"
              / = inline_svg "svg/jut-1.svg"
              span 5
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor6 type="checkbox" 
            label.switcher-control for="apartaments-floor6"
              / = inline_svg "svg/jut-1.svg"
              span 6
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor7 type="checkbox" 
            label.switcher-control for="apartaments-floor7"
              / = inline_svg "svg/jut-1.svg"
              span 7
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor8 type="checkbox" 
            label.switcher-control for="apartaments-floor8"
              / = inline_svg "svg/jut-1.svg"
              span 8
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor9 type="checkbox" 
            label.switcher-control for="apartaments-floor9"
              / = inline_svg "svg/jut-1.svg"
              span 9
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor10 type="checkbox" 
            label.switcher-control for="apartaments-floor10"
              / = inline_svg "svg/jut-1.svg"
              span 10
        .one-checkbox.small-w
          .checkbox
            input#apartaments-floor11 type="checkbox" 
            label.switcher-control for="apartaments-floor11"
              / = inline_svg "svg/jut-1.svg"
              span 11+

  .accordion-button
    span Ремонт:
    = inline_svg "svg/ic_keyboard_arrow_down_black_24px.svg"

  .accordion-inner
    .checkbox-box
      .inner
        .one-checkbox
          .checkbox
            input#checkbox-repairs1 type="checkbox" 
            label.switcher-control for="checkbox-repairs1"
              / = inline_svg "svg/jut-1.svg"
              span Євроремонт

        .one-checkbox
          .checkbox
            input#checkbox-repairs2 type="checkbox" 
            label.switcher-control for="checkbox-repairs2"
              / = inline_svg "svg/jut-1.svg"
              span Голі стіни
        .one-checkbox
          .checkbox
            input#checkbox-repairs3 type="checkbox" 
            label.switcher-control for="checkbox-repairs3"
              / = inline_svg "svg/jut-1.svg"
              span USSR Style

        .one-checkbox
          .checkbox
            input#checkbox-repairs4 type="checkbox" 
            label.switcher-control for="checkbox-repairs4"
              / = inline_svg "svg/jut-1.svg"
              span Бомжірня

app/views/application/_video_block.html.slim
.video-wrap
  .video-item
    iframe allowfullscreen="" class="youtube_video" data-video="http://www.youtube.com/embed/fSpzIO_Gx38?controls=2&amp;showinfo=0&amp;autoplay=1&amp;autohide=1" frameborder="0" id="video_4" src=""
    .video-control-info-panel.video_panel_4.active-youtube-panel
      .image style="background: url('#{asset_path("img/person.jpg")}')no-repeat center center;"
      .video-play-button data-video-id="video_4" data-video-panel="video_panel_4"
        = inline_svg "svg/play.svg"

app/views/pages/manager_one.html.slim
.manager-one-wrap.pt
  .breadcrumb-wrap
    .row
      .columns
        ul.breadcrumb
          li
            a href=root_path Головна
          li
            a href=managers_page_path Менеджери
          li
            a href="" Оксана Гаврилюк
  .row
    .columns
      a.go-back-btn.regular href=managers_page_path
        = inline_svg "svg/reply.svg"
        span До переліку менеджерів

  .manager-one-content.section-indent
    .row.columns-left
      .medium-5.large-3.columns
        .info-manager-box.apartanent
          .inner
            .manager-image.square
              .img-bg style="background-image: url(#{asset_path('img/manager-01.jpg')})"

            .manager-info
              h3.h3.blue оксана
              p Менеджер по квартирній та земельній нерухомості

              .call-box
                .svg-box.blue
                  = inline_svg "svg/telephone.svg"
                a.number.regular href="+380 96 458 7854" +380 96 458 7854
                a.number.regular href="+380 67 451 4568" +380 67 451 4568

              .mail-box
                .svg-box.blue
                  = inline_svg "svg/mail.svg"
                a.mail.regular href="/" 
                  |oksana
                  span.blue
                    |@
                  |matis.com

              h4.type.blue.smaller Житлова нерухомість
              .location.smaller Львів

              .call-me.blue-bg
                .title.larger Замовити дзвінок
                form
                  .input-field
                    input#first_name name="number"
                    label.smaller Ваш номер телефону?
                    span.bar
                    button.svg = inline_svg "svg/arrow_right.svg"

      .medium-7.large-9.columns
        .row
          - 5.times do |e|
            .medium-6.large-4.columns

              .one-apartament
                .square
                  a.img-bg href=apartaments_one_path style="background-image: url(#{asset_path('img/house3.jpg')})"
                  .type-apartanent.blue-bg
                    = inline_svg "svg/jut-3.svg"
                    span продаж

                .short-info.apartanent
                  h4.sub-title.blue Котедж
                  h2.h2 Касабланка
                  .map-position
                    p с. Сокільники, вул. Саксаганського, 24
                    a.blue href="/"
                      = inline_svg "svg/location"
                      | на карті
                  h3.price.blue
                    |1 250 00
                    span
                      |грн

                  .characteristics-info
                    .characteristics-one
                      = inline_svg "svg/squers.svg"
                      p.title.smaller Площа:
                      span.figures 240
                      span м
                      sup 2

                  .characteristics-info
                    .characteristics-one
                      = inline_svg "svg/kimnatu.svg"
                      p.title.smaller Кімнати:
                      span.figures 8